#!/bin/bash
# Build the executable and wrap it in a proper litepipe.app bundle so the drag
# helper has a real app to drag and macOS TCC has a stable identity to grant.
set -e
cd "$(dirname "$0")"

CONFIG="${1:-debug}"
swift build -c "$CONFIG"

APP="litepipe.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Resources/Info.plist "$APP/Contents/Info.plist"
cp ".build/$CONFIG/litepipe" "$APP/Contents/MacOS/litepipe"
chmod +x "$APP/Contents/MacOS/litepipe"

# The bridge an agent connects through. It sits beside the app rather than in
# Resources because a client spawns it as a program; shipping it here is what makes
# Connect work on a machine that is not the one it was written on.
cp ".build/$CONFIG/litepipe-mcp" "$APP/Contents/MacOS/litepipe-mcp"
chmod +x "$APP/Contents/MacOS/litepipe-mcp"

# Bundle the capture engine binary if present (built separately, see Engine.swift).
if [ -f "Resources/screenpipe" ]; then
  cp "Resources/screenpipe" "$APP/Contents/Resources/screenpipe"
  chmod +x "$APP/Contents/Resources/screenpipe"
  echo "bundled engine: Resources/screenpipe"
else
  echo "note: Resources/screenpipe not found - app will use dev fallback (~/projects/litepipe/target/release/screenpipe)"
fi

# Bundle UI sounds.
if [ -d "Resources/sounds" ]; then
  mkdir -p "$APP/Contents/Resources/sounds"
  cp Resources/sounds/*.wav "$APP/Contents/Resources/sounds/" 2>/dev/null && echo "bundled sounds"
fi

# Bundle the self-contained ffmpeg/ffprobe so capture works without Homebrew.
if [ -d "Resources/bin" ]; then
  mkdir -p "$APP/Contents/Resources/bin"
  cp Resources/bin/ffmpeg Resources/bin/ffprobe "$APP/Contents/Resources/bin/" 2>/dev/null
  chmod +x "$APP/Contents/Resources/bin/"* 2>/dev/null && echo "bundled ffmpeg/ffprobe"
fi

# Ship the third-party attribution notice alongside the app (MIT requires it).
[ -f "THIRD_PARTY_NOTICES.md" ] && cp THIRD_PARTY_NOTICES.md "$APP/Contents/Resources/THIRD_PARTY_NOTICES.md"

# App icon (generated by scripts/make-icon.swift; referenced by CFBundleIconFile).
[ -f "Resources/AppIcon.icns" ] && cp Resources/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns" && echo "bundled icon"

# Meeting service logos shown in the transcribe banner.
if [ -d "Resources/servicelogos" ]; then
  mkdir -p "$APP/Contents/Resources/servicelogos"
  cp Resources/servicelogos/*.png "$APP/Contents/Resources/servicelogos/" 2>/dev/null && echo "bundled service logos"
fi

# Sign with a stable local identity if present (so TCC grants persist across
# rebuilds); fall back to ad-hoc otherwise. Replace with an Ottic Developer ID
# for real white-label distribution.
SIGN_ID="litepipe-dev"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "$SIGN_ID"; then
  codesign --force --deep --sign "$SIGN_ID" "$APP"
  echo "signed with: $SIGN_ID (stable)"
else
  codesign --force --deep --sign - "$APP" 2>/dev/null || true
  echo "signed ad-hoc (no stable identity found)"
fi

echo "built ./$APP"
